#!/bin/bash
# Securthy Scanner — Installer
# Generated by Securthy Platform
# Client: %%CLIENT_NAME%%
# API Key: %%CLIENT_API_KEY%%

set -e

INSTALL_DIR="/opt/securthy"
BIN_DIR="/usr/local/bin"
PLATFORM_URL="%%PLATFORM_URL%%"
CLIENT_API_KEY="%%CLIENT_API_KEY%%"

# Find Go binary
GO_BIN=""
for p in /usr/local/go/bin/go /usr/bin/go /usr/local/bin/go $(which go 2>/dev/null); do
    if [ -f "$p" ]; then
        GO_BIN="$p"
        break
    fi
done

if [ -z "$GO_BIN" ]; then
    echo "[!] Go not found. Installing..."
    apt-get update -q && apt-get install -y golang-go
    GO_BIN=$(which go)
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Securthy Scanner — Installation                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "[*] Platform URL : $PLATFORM_URL"
echo "[*] Go binary    : $GO_BIN"
echo "[*] Install dir  : $INSTALL_DIR"
echo ""

# Copy source to install dir
mkdir -p "$INSTALL_DIR"
cp -r . "$INSTALL_DIR/"
cd "$INSTALL_DIR"

echo "[*] Installing dependencies..."
$GO_BIN mod tidy 2>/dev/null || true

echo "[*] Building binaries (API key baked in)..."

LDFLAGS="-X main.PlatformURL=$PLATFORM_URL -X main.ClientAPIKey=$CLIENT_API_KEY"

$GO_BIN build -ldflags "$LDFLAGS" -o scanner_bin        ./cmd/            && echo "  [+] scanner_bin"
$GO_BIN build -o employee_bin        ./employee/           && echo "  [+] employee_bin"
$GO_BIN build -o employee_packs_bin  ./employee_packs/     && echo "  [+] employee_packs_bin"
$GO_BIN build -o packs_bin           ./packs/              && echo "  [+] packs_bin"
$GO_BIN build -ldflags "$LDFLAGS" -o api_bin             ./api/            && echo "  [+] api_bin"
$GO_BIN build -o securthy            ./gui/                && echo "  [+] securthy (GUI)"

# Install CLI command
cat > "$BIN_DIR/securthy" << 'LAUNCHER'
#!/bin/bash
cd /opt/securthy
exec ./securthy "$@"
LAUNCHER
chmod +x "$BIN_DIR/securthy"

# Desktop shortcut
if [ -d "/usr/share/applications" ]; then
    cat > /usr/share/applications/securthy.desktop << 'DESKTOP'
[Desktop Entry]
Name=Securthy Scanner
Comment=Healthcare Network Security Assessment
Exec=bash -c "cd /opt/securthy && ./securthy"
Terminal=true
Type=Application
Categories=Network;Security;
DESKTOP
    echo "  [+] Desktop shortcut created"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Installation Complete!                                ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║   Run:  securthy                                        ║"
echo "║   Reports auto-sent to: $PLATFORM_URL"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
